# Placeholder Python code for Hands-On Activities (Part 2)

# 1️-Prompt Engineering for Chess Puzzles
# You can interact with an LLM API (like OpenAI) to generate chess puzzles and solutions

# Example placeholder function
def generate_chess_puzzle(difficulty):
    return f"Puzzle of {difficulty} difficulty with step-by-step solution."

for level in ['Easy', 'Medium', 'Hard']:
    print(generate_chess_puzzle(level))

# 2️-Compare Modern LLMs
llm_models = [
    {'Model': 'GPT-3', 'Release Year': 2020, 'Parameters': '175B', 'Key Innovations': 'Transformer, few-shot learning', 'Primary Applications': 'Text generation, chatbots'},
    {'Model': 'GPT-4', 'Release Year': 2023, 'Parameters': 'Unknown', 'Key Innovations': 'Multimodal, reasoning', 'Primary Applications': 'Text generation, reasoning, code'},
    {'Model': 'LLaMA', 'Release Year': 2023, 'Parameters': 'Various', 'Key Innovations': 'Efficient training on smaller datasets', 'Primary Applications': 'Research, text generation'},
    {'Model': 'PaLM', 'Release Year': 2022, 'Parameters': '540B', 'Key Innovations': 'Multitask, reasoning', 'Primary Applications': 'Text generation, reasoning'},
    {'Model': 'Claude', 'Release Year': 2023, 'Parameters': 'Unknown', 'Key Innovations': 'Safety, alignment', 'Primary Applications': 'Chatbots, reasoning'}
]

print("\nLLM Comparison Table:")
for model in llm_models:
    print(model)

# 3️-Compare Generative Architectures
generative_models = [
    {'Model Type': 'GAN', 'Used For': 'Image generation', 'Advantages': 'High-quality samples', 'Disadvantages': 'Training instability', 'Example Use Case': 'Deepfake generation'},
    {'Model Type': 'VAE', 'Used For': 'Data compression, generation', 'Advantages': 'Probabilistic latent space', 'Disadvantages': 'Blurred outputs', 'Example Use Case': 'Image reconstruction'},
    {'Model Type': 'Transformer', 'Used For': 'Sequence modeling', 'Advantages': 'Long-range dependencies', 'Disadvantages': 'Computationally expensive', 'Example Use Case': 'Text generation'},
    {'Model Type': 'Diffusion', 'Used For': 'Image generation', 'Advantages': 'High-fidelity outputs', 'Disadvantages': 'Slow sampling', 'Example Use Case': 'AI-generated artwork'}
]

print("\nGenerative Model Comparison:")
for gm in generative_models:
    print(gm)

# 4️-Discriminative vs Generative Classification Exercise
# Example placeholder
animal_description = "An animal with stripes that lives in the savannah"
print("Discriminative Task (Classification):", "Zebra")
print("Generative Task (Generate description):", "A similar animal with spots instead of stripes")

# 5-Latent Space Exploration (VAE Analogy)
object_name = 'Car'
essential_features = ['wheels', 'engine', 'body shape']
variable_features = ['color', 'size', 'interior design']
new_sample = 'blue compact car instead of red sedan'

print(f"Object: {object_name}")
print(f"Essential features: {essential_features}")
print(f"Variable features: {variable_features}")
print(f"New sample generated by changing variable features: {new_sample}")